apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: flask
spec:
  # Secret names are always required.
  secretName: flask
  dnsNames:
  - demo.shubhamk.online
  issuerRef:
    name: production-app
    kind: ClusterIssuer	
